version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - backend-data:/app/data
    environment:
      - NODE_ENV=development
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  backend-data: 